CLASS /eacm/update_tab DEFINITION

  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
ENDCLASS.



CLASS /EACM/UPDATE_TAB IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
UPDATE /EACM/ZPRDP SET vbeln = '0000019805'  WHERE vbeln = '19805'.
UPDATE /EACM/ZPRDP SET vbeln = '0000019813'  WHERE vbeln = '19813'.
UPDATE /EACM/ZPRDP SET vbeln = '0000019788'  WHERE vbeln = '19788'.
UPDATE /EACM/ZPRDP SET vbeln = '0000019816'  WHERE vbeln = '19816'.


*    DELETE FROM /EACM/ZPREN. "#EC CI_NOWHERE
*    DELETE FROM /EACM/ZPREN_d . "#EC CI_NOWHERE
*
*    out->write( |Tabelle ZPR22 e ZPR22_D pulite| ).

  ENDMETHOD.
ENDCLASS.
